pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        IMAGE_NAME = "yourdockerhubusername/demo-app"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/faizalfandi/kelompok_7.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:latest .'
            }
        }

        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }

        stage('Deploy with Helm') {
            steps {
                sh '''
                helm upgrade --install demo-app ./helm-chart/demo-app \
                  --set image.repository=$IMAGE_NAME \
                  --set image.tag=latest
                '''
            }
        }
    }
}
